apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: petvida
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root123
  MYSQL_DATABASE: petvida
  MYSQL_USER: aluno
  MYSQL_PASSWORD: senha123
